name: Trophies
version: 1.0
main: com.champmc.trophies.Trophies
api-version: 1.8.8
authors: [Squid]
depend: [SuperiorSkyblock2]
description: Mob Coin Trophies
commands:
  trophies:
    description: Admin command for the Trophies plugin
    permission: trophies.admin
    aliases: [trophy]

